apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: trivy-hybrid

inputs:
  binary-tar-path:
    description: 'Path to the binary to scan'
    required: true

  license:
    description: 'Flag to enable license scanning (true/false)'
    required: false
    default: ''

  cb_token:
    description: 'Token of Cloudbees'
    required: true

  cb_api_url:
    description: 'API to publish results'
    required: true
    default: 'https://api.saas-preprod.beescloud.com'

  gh_run_id:
    description: 'RUN id of the GHA'
    required: true

  gh_job_id:
    description: 'JOB id of the GHA'
    required: true

  gh_step_id:
    description: 'STEP id of the GHA'
    required: true



runs:
  using: composite
  steps:
    - name: Generate reference files 
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:d14621a0e281098b736a3d21cc92edd1fdc8b504
      with:
          entrypoint: assets-plugin-chain-utils
          args: generate-references --asset-type "BINARY" --tags "BINARY_CONTAINER" --binary-tar-path ${{ inputs.binary-tar-path }}
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ inputs.cb_token }}
          INPUT_CLOUDBEES_API_URL: ${{ inputs.cb_api_url }}
          INPUT_RUN_ID: ${{ inputs.gh_run_id }}

    - name: Run trivy compliance plugin
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-trivy-scanner:90ac7296abb2c0c877b3364b5ce21ccf50cb0353
      env:
          RUN_ID: ${{ inputs.gh_run_id }}
          JOB_ID: ${{ inputs.gh_job_id }}
          STEP_ID: ${{ inputs.gh_step_id }}
      run: |
        if [ "${{ inputs.license }}" = "true" ]; then
          /app/plugin-trivy-scanner -mode single -license
        else
          /app/plugin-trivy-scanner -mode single
        fi

    - name: Complete execution plan
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:d14621a0e281098b736a3d21cc92edd1fdc8b504
      id: process-outputs
      with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ inputs.cb_token }}
          INPUT_CLOUDBEES_API_URL: ${{ inputs.cb_api_url }}
          INPUT_RUN_ID: ${{ inputs.gh_run_id }}
