apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: trivy-hybrid

inputs:
  binary-tar-path:
    description: 'Path to the binary to scan'
    required: true

  license:
    description: 'Flag to enable license scanning (true/false)'
    required: false
    default: ''
outputs:
  critical-count:
    description: A string containing the number of Critical security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.critical-count}}
  very-high-count:
    description: A string containing the number of Very High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.very-high-count}}
  high-count:
    description: A string containing the number of High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.high-count}}
  medium-count:
    description: A string containing the number of Medium security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.medium-count}}
  low-count:
    description: A string containing the number of Low security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.low-count}}
  policy-subject:
    description: A json value containing the details about the vulnerability scan summary & details.
    value: ${{steps.process-outputs.outputs.policy-subject}}

runs:
  using: composite
  steps:
    - name: Clear asset store for container scan
      uses: docker://alpine:latest
      shell: sh
      run: |
        if [ -d "$CLOUDBEES_WORKSPACE/store" ]; then
          find $CLOUDBEES_WORKSPACE/store -mindepth 2 -maxdepth 2 \
            -type d ! -name "discovered-profile-findings" \
            -exec rm -rf {} +
          rm -rf $CLOUDBEES_WORKSPACE/store/binary-assets
          rm -rf $CLOUDBEES_WORKSPACE/store/request
        fi

    - name: Generate reference files
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:8ffcff74b5e47eb284c2b137a00b839db558fde1
      with:
          entrypoint: assets-plugin-chain-utils
          args: generate-references --asset-type "BINARY" --tags "BINARY_CONTAINER" --binary-tar-path ${{ inputs.binary-tar-path }}
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}

    - name: Run trivy compliance plugin
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-trivy-scanner:f8288fc51fab22c63b34cc5b22f84037e66e8f48
      continue-on-error: true
      env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
      run: |
        if [ "${{ inputs.license }}" = "true" ]; then
          /app/plugin-trivy-scanner -mode single -license
        else
          /app/plugin-trivy-scanner -mode single
        fi

    - name: Complete execution plan
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:8ffcff74b5e47eb284c2b137a00b839db558fde1
      id: process-outputs
      with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}
